export const dbAdminNav = [
  { label: 'Dashboard', href: '/db-admin/dashboard', section: 'Workspace' },
  { label: 'All campaigns', href: '/db-admin/batches', section: 'Workspace' },
  { label: 'Master file', href: '/db-admin/master-file', section: 'Workspace' },
  { label: 'Chat', href: '/db-admin/chat', section: 'Workspace' },
  { label: 'Personal notes', href: '/db-admin/personal-notes', section: 'Workspace' },
  { label: 'Attendance', href: '/db-admin/attendance', section: 'Operations' },
  { label: 'Leave apply', href: '/db-admin/leave-apply', section: 'Operations' },
  { label: 'Activity logs', href: '/db-admin/activity-logs', section: 'Operations' },
  {
    label: 'Disposition',
    href: '/db-admin/disposition',
    section: 'Operations',
    children: [
      { label: 'DNC', href: '/db-admin/disposition' },
      { label: '3M', href: '/db-admin/disposition/3m' },
      { label: '6M', href: '/db-admin/disposition/6m' },
    ],
  },
  { label: 'My data', href: '/db-admin/master-data', section: 'Data' },
  { label: 'Employee data', href: '/db-admin/master-data?tab=employee', section: 'Data' },
  { label: 'Suppression', href: '/db-admin/suppression', section: 'Data' },
  { label: 'Email verification', href: '/db-admin/bulk-email-verification', section: 'Data' },
  { label: 'Settings', href: '/db-admin/settings' },
];
