/** Official RPF master-data template column order (matches master-data-template.xlsx / RPF.xlsx). */
export const MASTER_DATA_TEMPLATE_HEADERS: readonly string[] = [
  'Date',
  'Lead Type',
  'Client Name',
  'Campaign Vertical',
  'Campaign Code',
  'Asset Title',
  'Salutation',
  'First Name',
  'Last Name',
  'Email ID',
  'Domain',
  'Job Title',
  'Job Title Level',
  'Job Title Department',
  'Company Name',
  'Industry Type',
  'Standard Industry',
  'Address 1',
  'City',
  'State',
  'Zip Code',
  'Country',
  'TimeZone',
  'SIC Code',
  'NAICS Code',
  'Address Type',
  'Phone Number',
  'Direct Number',
  'Exact Employee Size',
  'Employee Size Category',
  'Revenue Size',
  'Revenue Size Category',
  'Job Title Link',
  'Industry Type Link',
  'Employee Size Link',
  'Revenue Size Link',
  'Website',
  'Disposition',
] as const;
