export default () => ({
  NODE_ENV: process.env.NODE_ENV || 'development',
  PORT: parseInt(process.env.PORT || '4000', 10),
  API_PREFIX: process.env.API_PREFIX || 'api',
  API_VERSION: process.env.API_VERSION || 'v1',
  APP_NAME: process.env.APP_NAME || 'QuoreB2B CRM API',
  APP_URL: process.env.APP_URL || 'http://localhost:4000',
  CORS_ORIGINS: process.env.CORS_ORIGINS || 'http://localhost:3000,http://localhost:3001',
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_MAX_POOL_SIZE: parseInt(process.env.MONGODB_MAX_POOL_SIZE || '10', 10),
  MONGODB_SYNC_INDEXES: process.env.MONGODB_SYNC_INDEXES !== 'false',
  
  REDIS_ENABLED: process.env.REDIS_ENABLED !== 'false',
  REDIS_HOST: process.env.REDIS_HOST || 'localhost',
  REDIS_PORT: parseInt(process.env.REDIS_PORT || '6379', 10),
  REDIS_PASSWORD: process.env.REDIS_PASSWORD || '',
  REDIS_DB: parseInt(process.env.REDIS_DB || '0', 10),
  ELASTICSEARCH_ENABLED: process.env.ELASTICSEARCH_ENABLED === 'true',
  ELASTICSEARCH_NODE: process.env.ELASTICSEARCH_NODE || 'http://localhost:9200',
  ELASTICSEARCH_USERNAME: process.env.ELASTICSEARCH_USERNAME || '',
  ELASTICSEARCH_PASSWORD: process.env.ELASTICSEARCH_PASSWORD || '',
  ELASTICSEARCH_INDEX_PREFIX: process.env.ELASTICSEARCH_INDEX_PREFIX || 'quoreb2b',
  REDIS_CACHE_PREFIX: process.env.REDIS_CACHE_PREFIX || 'quoreb2b:cache',
  REDIS_CACHE_TTL_SECONDS: parseInt(process.env.REDIS_CACHE_TTL_SECONDS || '60', 10),
  REDIS_CACHE_TTL_LIVE_SECONDS: parseInt(process.env.REDIS_CACHE_TTL_LIVE_SECONDS || '15', 10),
  REDIS_CACHE_TTL_MEDIUM_SECONDS: parseInt(process.env.REDIS_CACHE_TTL_MEDIUM_SECONDS || '180', 10),
  REDIS_CACHE_TTL_LONG_SECONDS: parseInt(process.env.REDIS_CACHE_TTL_LONG_SECONDS || '600', 10),
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN || '15m',
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
  BULLMQ_PREFIX: process.env.BULLMQ_PREFIX || 'quoreb2b',
  THROTTLE_TTL: parseInt(process.env.THROTTLE_TTL || '60', 10),
  THROTTLE_LIMIT: parseInt(process.env.THROTTLE_LIMIT || '100', 10),
  SENTRY_DSN: process.env.SENTRY_DSN,
  SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT || 'development',
  SENTRY_TRACES_SAMPLE_RATE: parseFloat(process.env.SENTRY_TRACES_SAMPLE_RATE || '0.1'),
  LOG_LEVEL: process.env.LOG_LEVEL || 'debug',
  SOCKET_CORS_ORIGINS: process.env.SOCKET_CORS_ORIGINS,
  BULK_EMAIL_SMTP_FROM: process.env.BULK_EMAIL_SMTP_FROM,
  BULK_EMAIL_DOMAIN_CACHE_TTL_MS: parseInt(
    process.env.BULK_EMAIL_DOMAIN_CACHE_TTL_MS || '3600000',
    10,
  ),
  BULK_EMAIL_DNS_NEGATIVE_CACHE_TTL_MS: parseInt(
    process.env.BULK_EMAIL_DNS_NEGATIVE_CACHE_TTL_MS || '300000',
    10,
  ),
  BULK_EMAIL_MAX_ROWS_PER_BATCH: parseInt(
    process.env.BULK_EMAIL_MAX_ROWS_PER_BATCH || '100000',
    10,
  ),
  BULK_EMAIL_SYNC_MAX_ROWS: parseInt(process.env.BULK_EMAIL_SYNC_MAX_ROWS || '200', 10),
  BULK_EMAIL_SMTP_TIMEOUT_MS: parseInt(
    process.env.BULK_EMAIL_SMTP_TIMEOUT_MS || '10000',
    10,
  ),
  BULK_EMAIL_STOP_ON_VALID: process.env.BULK_EMAIL_STOP_ON_VALID !== 'false',
  BULK_EMAIL_QUEUE_CONCURRENCY: parseInt(
    process.env.BULK_EMAIL_QUEUE_CONCURRENCY || '8',
    10,
  ),
  BULK_EMAIL_PROSPECT_CONCURRENCY: parseInt(
    process.env.BULK_EMAIL_PROSPECT_CONCURRENCY || '8',
    10,
  ),
  BULK_EMAIL_PATTERN_CONCURRENCY: parseInt(
    process.env.BULK_EMAIL_PATTERN_CONCURRENCY || '6',
    10,
  ),
  BULK_EMAIL_MAX_PATTERNS: parseInt(process.env.BULK_EMAIL_MAX_PATTERNS || '12', 10),
  BULK_EMAIL_SKIP_CATCH_ALL_PROBE: process.env.BULK_EMAIL_SKIP_CATCH_ALL_PROBE === 'true',
  BULK_EMAIL_DISPOSABLE_DOMAINS_PATH: process.env.BULK_EMAIL_DISPOSABLE_DOMAINS_PATH,
  BULK_EMAIL_MX_ONLY_FALLBACK: process.env.BULK_EMAIL_MX_ONLY_FALLBACK !== 'false',
  BULK_EMAIL_STRICT_MAILBOX_REJECT: process.env.BULK_EMAIL_STRICT_MAILBOX_REJECT === 'true',
  /** In-house only — no third-party verification API */
  BULK_EMAIL_VERIFICATION_PROVIDER: 'internal',
  /** false = RCPT TO mailbox check (matches ZeroBounce mailbox layer) */
  BULK_EMAIL_SKIP_SMTP_PROBE: process.env.BULK_EMAIL_SKIP_SMTP_PROBE === 'true',
});
